name: Windows Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Download and Install OpenSSL
        run: |
          Invoke-WebRequest -Uri "https://slproweb.com/download/Win64OpenSSL_Light-3_0_11.exe" -OutFile "openssl_installer.exe"
          Start-Process "openssl_installer.exe" -ArgumentList "/silent /install" -NoNewWindow -Wait

      - name: List OpenSSL directory
        run: dir "C:/Program Files/OpenSSL-Win64"
        
      - name: Set OPENSSL_ROOT_DIR environment variable
        run: echo "OPENSSL_ROOT_DIR=C:/Program Files/OpenSSL-Win64/" >> $GITHUB_ENV

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          install-deps: 'true'
          modules: 'qtwebengine qtwebchannel qtpositioning'

      - name: Configure Project
        run: qt-cmake -DOPENSSL_ROOT_DIR="C:/Program Files/OpenSSL-Win64/" -DOPENSSL_LIBRARIES="C:/Program Files/OpenSSL-Win64/lib/" -S . -B ./build

      - name: Build Project
        working-directory: ./build
        run: cmake --build .

      - name: List build directory
        run: dir ./build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./build/Debug/InstaOrder.exe  # Adjust this path if needed
